# local self host with n8n
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_DATABASE=n8n
      - GENERIC_TIMEZONE=Asia/Bangkok
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true  
      - N8N_RUNNERS_ENABLED=true 
      # --- ⚠️ ตั้งค่าส่วนนี้ใน Checkpoint 6 เมื่อทำ Reverse Proxy ---
      - N8N_HOST=8aa01f4f0292.ngrok-free.app # <-- ✏️ ใส่ Hostname จาก ngrok (ไม่ต้องมี https://)
      - N8N_PROTOCOL=https
      - WEBHOOK_URL= https://8aa01f4f0292.ngrok-free.app # <-- ✏️ ใส่ URL เต็มๆ จาก ngrok
      - N8N_TRUST_PROXY=true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  n8n_data: