services:
  # 1. Database Service (PostgreSQL)
  #    - Render จะสร้างชื่อฐานข้อมูลและผู้ใช้ให้ตรงกับ 'name' โดยอัตโนมัติ
  - type: pserv
    name: postgres-db
    runtime: postgres # ⭐️ กลับมาใช้ 'postgres' ถูกต้องแล้ว
    plan: free
    autoDeploy: false

  # 2. n8n Web Service
  - type: web
    name: n8n
    plan: free
    healthCheckPath: /healthz
    image:
      url: n8nio/n8n

    envVars:
      # --- กำหนดให้ n8n ใช้ฐานข้อมูล PostgreSQL ---
      - key: DB_TYPE
        value: postgresdb

      # --- ดึงค่าการเชื่อมต่อ DB จาก Service ด้านบน ---
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: postgres-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: postgres-db
          property: database # Render จะสร้างค่านี้ให้เอง
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: postgres-db
          property: user # Render จะสร้างค่านี้ให้เอง
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: postgres-db
          property: password # Render จะสร้างค่านี้ให้เอง

      # --- การตั้งค่าอื่นๆ ยังคงเดิม ---
      - key: N8N_TRUST_PROXY
        value: true
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: WEBHOOK_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok

