# Blueprint Spec Version
version: "1"

# 1. Database Service Definition
databases:
  - name: postgres-db
    plan: free
    # autoDeploy: false # ⭐️ ลบบรรทัดนี้ออก

# 2. Web Service Definition
services:
  - type: web
    name: n8n
    plan: free
    healthCheckPath: /healthz
    image:
      url: n8nio/n8n

    envVars:
      # --- กำหนดให้ n8n ใช้ฐานข้อมูล PostgreSQL ---
      - key: DB_TYPE
        value: postgresdb

      # --- ดึงค่าการเชื่อมต่อจาก 'databases' ด้านบน ---
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: postgres-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password

      # --- การตั้งค่าอื่นๆ ยังคงเดิม ---
      - key: N8N_TRUST_PROXY
        value: true
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: WEBHOOK_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok

