services:
  # 1. Database Service (PostgreSQL)
  #    - แก้ไข `runtime` เป็น `database` และเพิ่ม `databaseName` กับ `user`
  - type: pserv
    name: postgres-db
    runtime: database # ⭐️ แก้ไขจาก postgres เป็น database
    databaseName: n8n_data # ⭐️ เพิ่ม: ชื่อฐานข้อมูล
    user: n8n_user # ⭐️ เพิ่ม: ชื่อผู้ใช้
    plan: free
    autoDeploy: false

  # 2. n8n Web Service
  - type: web
    name: n8n
    plan: free
    healthCheckPath: /healthz
    image:
      url: n8nio/n8n

    envVars:
      # --- กำหนดให้ n8n ใช้ฐานข้อมูล PostgreSQL ---
      - key: DB_TYPE
        value: postgresdb

      # --- ดึงค่าการเชื่อมต่อ DB แยกกันทีละส่วน ---
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: postgres-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: postgres-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: postgres-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: postgres-db
          property: password

      # --- การตั้งค่าอื่นๆ ยังคงเดิม ---
      - key: N8N_TRUST_PROXY
        value: true
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: WEBHOOK_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok

